<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <%@ page import="javax.sql.*"%>
    <%@ page import="java.sql.*"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>

<%
		
		String UID_b = request.getParameter("UID_f");
		String action = request.getParameter("action");

		//Revenue generated by a flight
		if(action.equals("1"))
		{
			
			try {

				//past reservation
				Class.forName("com.mysql.jdbc.Driver"); 
				java.sql.Connection con = DriverManager.getConnection("jdbc:mysql:" + "//groupone.chnfim8mzrlx.us-east-2.rds.amazonaws.com:3306/" + "GroupOne336","cody","codychen1005!"); 
				Statement stmt = con.createStatement();
				/****right now we know the attribute trip_type  = oneway, so we skip it and put it as a conditional statement***/
				//String Query = "SELECT current_date()";

				String strQuery = "SELECT o.customerID, f.flight_number,f.total_fare, f.departure_airport, f.arrival_airport FROM Relates_to as r join Flight as f using(flight_number) join Ticket as t using (ticket_number) join Owns_by as o using(ticket_number) where o.customerID=('"+UID_b+"') and r.departure_date <= (select current_date());";
				ResultSet rs = stmt.executeQuery(strQuery);
				
				out.print("<table style = 'width:50%'>");

					out.print("<tr>");
					
					out.print("<td>");
					out.print("customerID");
					out.print("</td>");
					
					out.print("<td>");
					out.print("Flight number");
					out.print("</td>");
					
					out.print("<td>");
					out.print("Total fare");
					out.print("</td>");
					
					out.print("<td>");
					out.print("Departure airport");
					out.print("</td>");
					
					out.print("<td>");
					out.print("Arrival airport");
					out.print("</td>");
		
					
					out.print("</tr>");
					
					while (rs.next()) 
					{
						
						out.print("<tr>");
						
						out.print("<td>");
						out.print(rs.getString("customerID"));
						out.print("</td>");
						
						out.print("<td>");
						out.print(rs.getString("flight_number"));
						out.print("</td>");
						
						out.print("<td>");
						out.print(rs.getString("total_fare"));
						out.print("</td>");
						
						out.print("<td>");
						out.print(rs.getString("departure_airport"));
						out.print("</td>");
						
						out.print("<td>");
						out.print(rs.getString("arrival_airport"));
						out.print("</td>");
					
						out.print("</tr>");
						
					}
				out.print("</table>");

			
			} catch (Exception e) {
				out.print(e);
			}
			
		}
		
		//
		else if(action.equals("2"))
		{
			try {

				//Get the database connection
				Class.forName("com.mysql.jdbc.Driver"); 
				java.sql.Connection con = DriverManager.getConnection("jdbc:mysql:" + "//groupone.chnfim8mzrlx.us-east-2.rds.amazonaws.com:3306/" + "GroupOne336","cody","codychen1005!"); 
				Statement stmt = con.createStatement();
				/****right now we know the attribute trip_type  = oneway, so we skip it and put it as a conditional statement***/

				String strQuery = "SELECT o.customerID, f.flight_number,f.total_fare, f.departure_airport, f.arrival_airport FROM Relates_to as r join Flight as f using(flight_number) join Ticket as t using (ticket_number) join Owns_by as o using(ticket_number) where o.customerID=('"+UID_b+"') and r.departure_date >= (select current_date());";
				ResultSet rs = stmt.executeQuery(strQuery);
				
				out.print("<table style = 'width:50%'>");

					out.print("<tr>");
					
					out.print("<td>");
					out.print("CustomerID");
					out.print("</td>");
					
					out.print("<td>");
					out.print("Flight number");
					out.print("</td>");
					
					out.print("<td>");
					out.print("Total fare");
					out.print("</td>");
					
					out.print("<td>");
					out.print("Departure airport");
					out.print("</td>");
					
					out.print("<td>");
					out.print("Arrival airport");
					out.print("</td>");
					
		
					
					out.print("</tr>");
					
					while (rs.next()) 
					{
						
						out.print("<tr>");
						
						out.print("<td>");
						out.print(rs.getString("customerID"));
						out.print("</td>");
						
						out.print("<td>");
						out.print(rs.getString("flight_number"));
						out.print("</td>");
						
						out.print("<td>");
						out.print(rs.getString("total_fare"));
						out.print("</td>");
						
						out.print("<td>");
						out.print(rs.getString("departure_airport"));
						out.print("</td>");
						
						out.print("<td>");
						out.print(rs.getString("arrival_airport"));
						out.print("</td>");
						
					
						out.print("</tr>");
						
					}
				out.print("</table>");

			
			} catch (Exception e) {
				out.print(e);
			}
		}
		
		else{
			out.println("Error"); 
		}
	
		out.print("<a href=" + "http://localhost:8080/336test/alteredFiles/viewAccount_f.jsp><mark>back</mark></a>");
	%>


</body>
</html>