<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <%@ page import="javax.sql.*"%>
    <%@ page import="java.sql.*"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>

<%
		try {

			//Get the database connection
			Class.forName("com.mysql.jdbc.Driver"); 
			java.sql.Connection con = DriverManager.getConnection("jdbc:mysql:" + "//groupone.chnfim8mzrlx.us-east-2.rds.amazonaws.com:3306/" + "GroupOne336","cody","codychen1005!"); 
			Statement stmt = con.createStatement();
			/****right now we know the attribute trip_type  = oneway, so we skip it and put it as a conditional statement***/

			String strQuery = "SELECT tb.customerID, MAX(tb.money) as revenue from (SELECT c.customerID,sum(t.total_fare) as money FROM Owns_by as o join Customer as c using(customerID) join Ticket as t using (ticket_number) GROUP BY customerID order by money DESC) as tb;";
			ResultSet rs = stmt.executeQuery(strQuery);
			
			out.print("<table style = 'width:50%'>");

				out.print("<tr>");
				
				out.print("<td>");
				out.print("CustomerID");
				out.print("</td>");
				
				out.print("<td>");
				out.print("Total revenue generated by this customer");
				out.print("</td>");
				
	
				
				out.print("</tr>");
				
				while (rs.next()) 
				{
					
					out.print("<tr>");
					
					out.print("<td>");
					out.print(rs.getString("customerID"));
					out.print("</td>");
					
					out.print("<td>");
					out.print(rs.getString("revenue"));
					out.print("</td>");
					
				
					out.print("</tr>");
					
				}
			out.print("</table>");
			out.print("<a href=" + "http://localhost:8080/336test/adminFunction/revenueGeneratedBy_f.jsp><mark>back</mark></a>");
		
		} catch (Exception e) {
			out.print(e);
		}
	%>

</body>
</html>