<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>

<h2>
	Please Select an attribute below:
	</h2>
	<br>
	<form method="post" action="revenueGeneratedBy_b.jsp">
		<select name="action" size=1>
			<option value="1">Revenue generated by a flight</option>
			<option value="2">Revenue generated by an airline company</option>
			<option value="3">Revenue generated by a customer</option>
		</select>&nbsp;
		<table>
		
			<tr>
				<td>Corresponding value</td>
				<td><input type="text" name="value_f"></td>
			</tr>
			
		</table>
		<br> <input type="submit" value="submit">
	</form>
	<a href="http://localhost:8080/336test/adminFunction/produceReservationList_f.jsp"> <mark>Back to product reservation page</mark></a>
	<br>

</body>
</html>