<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <%@ page import="javax.sql.*"%>
    <%@ page import="java.sql.*"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>

<%
		
		String value_f = request.getParameter("value_f");
		String action = request.getParameter("action");

		//Revenue generated by a flight
		if(action.equals("1"))
		{
			
			try {

				//Get the database connection
				Class.forName("com.mysql.jdbc.Driver"); 
				java.sql.Connection con = DriverManager.getConnection("jdbc:mysql:" + "//groupone.chnfim8mzrlx.us-east-2.rds.amazonaws.com:3306/" + "GroupOne336","cody","codychen1005!"); 
				Statement stmt = con.createStatement();
				/****right now we know the attribute trip_type  = oneway, so we skip it and put it as a conditional statement***/

				String strQuery = "SELECT f.flight_number,t.total_fare FROM Relates_to as r join Flight as f using(flight_number) join Ticket as t using (ticket_number) where f.flight_number=('"+value_f+"');";
				ResultSet rs = stmt.executeQuery(strQuery);
				
				out.print("<table style = 'width:50%'>");

					out.print("<tr>");
					
					out.print("<td>");
					out.print("Flight_number");
					out.print("</td>");
					
					out.print("<td>");
					out.print("Money of each ticket sold by this flight");
					out.print("</td>");
					
		
					
					out.print("</tr>");
					
					while (rs.next()) 
					{
						
						out.print("<tr>");
						
						out.print("<td>");
						out.print(rs.getString("flight_number"));
						out.print("</td>");
						
						out.print("<td>");
						out.print(rs.getString("total_fare"));
						out.print("</td>");
						
					
						out.print("</tr>");
						
					}
				out.print("</table>");

			
			} catch (Exception e) {
				out.print(e);
			}
			
		}
		
		//Revenue generated by an airline company
		else if(action.equals("2"))
		{
			try {

				//Get the database connection
				Class.forName("com.mysql.jdbc.Driver"); 
				java.sql.Connection con = DriverManager.getConnection("jdbc:mysql:" + "//groupone.chnfim8mzrlx.us-east-2.rds.amazonaws.com:3306/" + "GroupOne336","cody","codychen1005!"); 
				Statement stmt = con.createStatement();
				/****right now we know the attribute trip_type  = oneway, so we skip it and put it as a conditional statement***/

				String strQuery = "SELECT a.companyID, t.total_fare FROM Operate o join Flight as f using(flight_number) join Airline_Company as a using(companyID) join Relates_to as r using(flight_number) join Ticket as t using (ticket_number) where a.companyID=('"+value_f+"');";
				ResultSet rs = stmt.executeQuery(strQuery);
				
				out.print("<table style = 'width:50%'>");

					out.print("<tr>");
					
					out.print("<td>");
					out.print("CompanyID");
					out.print("</td>");
					
					out.print("<td>");
					out.print("Money of each ticket sold by this company");
					out.print("</td>");
					
		
					
					out.print("</tr>");
					
					while (rs.next()) 
					{
						
						out.print("<tr>");
						
						out.print("<td>");
						out.print(rs.getString("companyID"));
						out.print("</td>");
						
						out.print("<td>");
						out.print(rs.getString("total_fare"));
						out.print("</td>");
						
					
						out.print("</tr>");
						
					}
				out.print("</table>");

			
			} catch (Exception e) {
				out.print(e);
			}
		}
		
		//Revenue generated by a customer
		else if (action.equals("3"))
		{
			try {

				//Get the database connection
				Class.forName("com.mysql.jdbc.Driver"); 
				java.sql.Connection con = DriverManager.getConnection("jdbc:mysql:" + "//groupone.chnfim8mzrlx.us-east-2.rds.amazonaws.com:3306/" + "GroupOne336","cody","codychen1005!"); 
				Statement stmt = con.createStatement();
				/****right now we know the attribute trip_type  = oneway, so we skip it and put it as a conditional statement***/

				String strQuery = "SELECT c.customerID,t.total_fare FROM Owns_by as o join Customer as c using(customerID) join Ticket as t using (ticket_number) where c.customerID=('"+value_f+"');";
				ResultSet rs = stmt.executeQuery(strQuery);
				
				out.print("<table style = 'width:50%'>");

					out.print("<tr>");
					
					out.print("<td>");
					out.print("CustomerID");
					out.print("</td>");
					
					out.print("<td>");
					out.print("Price of ticket this customer bought");
					out.print("</td>");
					
		
					
					out.print("</tr>");
					
					while (rs.next()) 
					{
						
						out.print("<tr>");
						
						out.print("<td>");
						out.print(rs.getString("customerID"));
						out.print("</td>");
						
						out.print("<td>");
						out.print(rs.getString("total_fare"));
						out.print("</td>");
						
					
						out.print("</tr>");
						
					}
				out.print("</table>");

			
			} catch (Exception e) {
				out.print(e);
			}
		}
		
		else{
			out.println("Error"); 
		}
	
		out.print("<a href=" + "http://localhost:8080/336test/adminFunction/revenueGeneratedBy_f.jsp><mark>back</mark></a>");
	%>

</body>
</html>